import React,{useState} from 'react';
import {cmsText} from '../cms/content.ts';
import {PageId} from '../types.ts';
import {HeroVideo} from '../components/HeroVideo.tsx';
import {ContactForm} from '../components/ContactForm.tsx';
import {ArrowRight,FileText,MapPin,Sun,Moon,Sparkles,DoorOpen} from 'lucide-react';
interface HomePageProps {onNavigate:(page:PageId,subHash?:string)=>void;onOpenConsultation:()=>void;onOpenPrivacy:()=>void}
const wrap='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8';
const primary='inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg bg-[#0E4637] text-[#E6F15A] font-semibold text-sm hover:bg-[#17211C]';
const secondary='inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg border border-[#0E4637]/25 text-[#0E4637] font-semibold text-sm hover:bg-[#CFE3C4]/25';
export const HomePage:React.FC<HomePageProps>=({onNavigate,onOpenConsultation,onOpenPrivacy})=>{
 const [scene,setScene]=useState(0);
 const scenes=[
  {icon:Sun,title:cmsText('HomePage-v2-dinner','Kolacja'),light:cmsText('HomePage-v2-dinner-light','Światło nad stołem, delikatne tło w salonie.'),shades:cmsText('HomePage-v2-dinner-shades','Zasłony w pozycji wybranej przez domowników.'),control:cmsText('HomePage-v2-dinner-control','Jedno naciśnięcie przycisku sceny. Jasność można zmienić ręcznie.')},
  {icon:Moon,title:cmsText('HomePage-v2-film','Film'),light:cmsText('HomePage-v2-film-light','Przygaszone oprawy, dyskretne światło orientacyjne.'),shades:cmsText('HomePage-v2-film-shades','Osłony ograniczają odbicia na ekranie.'),control:cmsText('HomePage-v2-film-control','Scena z przycisku lub panelu. Sterowanie sprzętem AV wymaga uzgodnionej integracji.')},
  {icon:Sparkles,title:cmsText('HomePage-v2-clean','Sprzątanie'),light:cmsText('HomePage-v2-clean-light','Jasne oświetlenie całej strefy dziennej.'),shades:cmsText('HomePage-v2-clean-shades','Położenie osłon pozostaje pod kontrolą użytkownika.'),control:cmsText('HomePage-v2-clean-control','Scena uruchamiana ręcznie; sposób powrotu do codziennych ustawień ustalamy w projekcie.')},
  {icon:DoorOpen,title:cmsText('HomePage-v2-away','Wyjście'),light:cmsText('HomePage-v2-away-light','Wyłączenie wybranych obwodów, z pominięciem potrzebnych urządzeń.'),shades:cmsText('HomePage-v2-away-shades','Osłony według ustalonego scenariusza i zabezpieczeń pogodowych.'),control:cmsText('HomePage-v2-away-control','Przycisk przy wyjściu. Reakcje ogrzewania i alarmu uzgadniamy osobno.')}
 ];
 const chosen=scenes[scene];
 const paths=[
  {id:'architects' as PageId,title:cmsText('HomePage-v2-arch-title','Dla architektów'),body:cmsText('HomePage-v2-arch-body','Karta funkcji, rozmieszczenie sterowania i dobór osprzętu do wnętrza. Zobacz materiały do rozmowy z klientem.'),cta:cmsText('HomePage-v2-arch-cta','Poznaj współpracę')},
  {id:'homes' as PageId,title:cmsText('HomePage-v2-home-title','Dla inwestorów'),body:cmsText('HomePage-v2-home-body','Zaplanuj działanie domu lub apartamentu. Ustal priorytety i sposób obsługi, zanim wybierzesz urządzenia.'),cta:cmsText('HomePage-v2-home-cta','Zaplanuj funkcje domu')},
  {id:'offices' as PageId,title:cmsText('HomePage-v2-office-title','Dla biur i fit-out'),body:cmsText('HomePage-v2-office-body','Światło, komfort i sceny sal spotkań dopasowane do użytkowników oraz wymagań instalacji budynku.'),cta:cmsText('HomePage-v2-office-cta','Poznaj automatykę biura')}
 ];
 return <div className="space-y-0">
  <HeroVideo />
  <section className="relative overflow-hidden bg-[#F7F8F5] pt-8 pb-12 lg:pt-10 lg:pb-16 border-b border-[#17211C]/10">
   <div className="absolute inset-0 bg-grid-subtle opacity-70 pointer-events-none"/>
   <div className={wrap+' relative grid lg:grid-cols-12 gap-10 items-center'}>
    <div className="lg:col-span-8 space-y-6">
     <p className="text-xs uppercase tracking-widest text-[#0E4637] font-semibold">{cmsText('HomePage-v2-kicker','KNX · partner architektów i inwestorów')}</p>
     <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold font-display tracking-tight leading-[1.1] text-balance">{cmsText('HomePage-v2-title','Projektujesz wnętrze. My pomagamy zaplanować, jak będzie działać.')}</h1>
     <p className="text-lg leading-relaxed text-[#17211C]/75 max-w-2xl">{cmsText('HomePage-v2-intro','Łączymy światło, osłony i temperaturę w scenariusze dopasowane do codzienności. Zaczynamy od rzutu i rozmowy — z architektem, inwestorem oraz wykonawcami.')}</p>
     <div className="flex flex-wrap gap-3"><button onClick={onOpenConsultation} className={primary}>{cmsText('HomePage-v2-talk','Omów projekt')}<ArrowRight size={17}/></button><button onClick={()=>onNavigate('architects','pakiet')} className={secondary}>{cmsText('HomePage-v2-pack','Zobacz pakiet dla architekta')}</button></div>
    </div>
    <aside className="lg:col-span-4 rounded-2xl bg-[#0E4637] text-white p-7 sm:p-8 space-y-5">
     <FileText className="text-[#E6F15A]" size={32}/><h2 className="text-2xl font-display font-semibold">{cmsText('HomePage-v2-outcome-title','Od pomysłu do zapisanych decyzji.')}</h2>
     <ul className="space-y-4 text-sm text-white/85">{[cmsText('HomePage-v2-outcome-1','Co ma robić każdy przycisk i scena.'),cmsText('HomePage-v2-outcome-2','Gdzie umieścić punkty sterowania.'),cmsText('HomePage-v2-outcome-3','Co uzgodnić z elektrykiem i pozostałymi branżami.')].map(x=><li key={x} className="flex gap-3"><span className="text-[#E6F15A]">↗</span>{x}</li>)}</ul>
     <p className="text-xs text-[#CFE3C4] border-t border-white/20 pt-4">{cmsText('HomePage-v2-location','Salon w Warszawie · projekty w Polsce')}</p>
    </aside>
   </div>
  </section>
  <section className="py-12 sm:py-16 bg-white border-b border-[#17211C]/10"><div className={wrap}>
   <p className="text-xs uppercase tracking-widest text-[#0E4637] font-semibold mb-3">{cmsText('HomePage-v2-paths-kicker','Wybierz punkt wyjścia')}</p>
   <h2 className="text-3xl font-display font-bold mb-8">{cmsText('HomePage-v2-paths-title','Ten sam projekt. Różne perspektywy.')}</h2>
   <div className="grid md:grid-cols-3 gap-5">{paths.map((item,i)=><article key={item.id} className={'p-7 rounded-2xl border flex flex-col '+(i===0?'bg-[#E6F15A] border-[#E6F15A]':'bg-[#F7F8F5] border-[#17211C]/10')}><span className="text-sm font-mono text-[#0E4637]">0{i+1}</span><h3 className="text-2xl font-display font-bold mt-3 mb-4">{item.title}</h3><p className="text-sm leading-relaxed text-[#17211C]/75 flex-grow">{item.body}</p><button className="text-left text-sm font-semibold mt-6 flex items-center gap-2 text-[#0E4637]" onClick={()=>onNavigate(item.id)}>{item.cta}<ArrowRight size={16}/></button></article>)}</div>
  </div></section>
  <section className="py-12 sm:py-16"><div className={wrap+' grid lg:grid-cols-2 gap-8 items-start'}>
   <div className="space-y-5"><p className="text-xs uppercase tracking-widest text-[#0E4637] font-semibold">{cmsText('HomePage-v2-scenes-kicker','Przykładowa karta pomieszczenia')}</p><h2 className="text-3xl sm:text-4xl font-display font-bold">{cmsText('HomePage-v2-scenes-title','Jeden salon. Cztery scenariusze.')}</h2><p className="text-[#17211C]/75 leading-relaxed">{cmsText('HomePage-v2-scenes-intro','Najpierw ustalamy, jak korzystasz z przestrzeni. Dopiero potem dobieramy przyciski, oprawy i sposób sterowania.')}</p><p className="text-sm text-[#17211C]/65">{cmsText('HomePage-v2-scenes-note','To ilustracja koncepcji, nie sterowanie rzeczywistą instalacją. Funkcje zależą od urządzeń, projektu i ustaleń z użytkownikami.')}</p><button onClick={()=>onNavigate('architects','pakiet')} className={secondary}>{cmsText('HomePage-v2-scenes-pack','Otwórz przykładową kartę')}<FileText size={17}/></button></div>
   <div className="bg-white border border-[#17211C]/10 rounded-2xl overflow-hidden shadow-sm"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 bg-[#CFE3C4]/20" role="group" aria-label={cmsText('HomePage-v2-scenes-label','Wybierz przykładowy scenariusz')}>{scenes.map((item,i)=><button key={i} onClick={()=>setScene(i)} aria-pressed={scene===i} className={'flex flex-col items-center gap-2 p-3 text-sm rounded-lg font-medium '+(scene===i?'bg-[#0E4637] text-[#E6F15A]':'text-[#0E4637] hover:bg-white')}><item.icon size={20}/>{item.title}</button>)}</div><div className="p-6 sm:p-8 space-y-5" aria-live="polite"><h3 className="text-2xl font-bold font-display">{chosen.title}</h3><dl className="space-y-5 text-sm"><div><dt className="font-semibold text-[#0E4637] mb-1">{cmsText('HomePage-v2-light-label','Światło')}</dt><dd className="text-[#17211C]/75">{chosen.light}</dd></div><div><dt className="font-semibold text-[#0E4637] mb-1">{cmsText('HomePage-v2-shades-label','Osłony')}</dt><dd className="text-[#17211C]/75">{chosen.shades}</dd></div><div><dt className="font-semibold text-[#0E4637] mb-1">{cmsText('HomePage-v2-control-label','Obsługa')}</dt><dd className="text-[#17211C]/75">{chosen.control}</dd></div></dl></div></div>
  </div></section>
  <section className="bg-[#17211C] text-white py-12 sm:py-16"><div className={wrap+' grid lg:grid-cols-2 gap-10 items-center'}><div><MapPin className="text-[#E6F15A] mb-5" size={30}/><p className="text-xs uppercase tracking-widest text-[#E6F15A] mb-3">{cmsText('HomePage-v2-showroom-kicker','Salon sprzedaży · Warszawa')}</p><h2 className="text-3xl sm:text-4xl font-display font-bold">{cmsText('HomePage-v2-showroom-title','Przyjdź z projektem. Możesz też przyjść z klientem.')}</h2><p className="text-white/75 mt-5 leading-relaxed">{cmsText('HomePage-v2-showroom-body','Porozmawiajmy o wyglądzie osprzętu, funkcjach i kolejności decyzji. Przed wizytą uzgodnimy temat spotkania oraz dostępność interesujących Cię próbek.')}</p></div><div className="rounded-2xl border border-white/15 p-7 sm:p-8 space-y-5"><p className="text-2xl font-display font-semibold">{cmsText('HomePage-v2-showroom-address','Konwaliowa 7 lok. 103')}</p><p className="text-[#CFE3C4]">{cmsText('HomePage-v2-showroom-city','03-194 Warszawa')}</p><p className="text-sm text-white/75">{cmsText('HomePage-v2-showroom-appointment','Spotkania po wcześniejszym uzgodnieniu.')}</p><button onClick={()=>onNavigate('showroom')} className="inline-flex gap-2 items-center bg-[#E6F15A] text-[#0E4637] rounded-lg px-5 py-3 text-sm font-semibold">{cmsText('HomePage-v2-showroom-cta','Zaplanuj wizytę')}<ArrowRight size={17}/></button></div></div></section>
  <section className="py-12 sm:py-16 bg-white"><div className={wrap}><div className="flex flex-wrap items-end justify-between gap-5 mb-8"><div><p className="text-xs uppercase tracking-widest text-[#0E4637] font-semibold mb-3">{cmsText('HomePage-v2-process-kicker','Jasny zakres współpracy')}</p><h2 className="text-3xl font-display font-bold">{cmsText('HomePage-v2-process-title','Wiesz, co ustalamy i co dalej.')}</h2></div><button onClick={()=>onNavigate('about')} className={secondary}>{cmsText('HomePage-v2-process-cta','Jak pracujemy')}<ArrowRight size={16}/></button></div><div className="grid sm:grid-cols-3 gap-5">{[{title:cmsText('HomePage-v2-step-1','1. Rzut i potrzeby'),text:cmsText('HomePage-v2-step-1-body','Etap inwestycji, sposób korzystania z pomieszczeń i pytania do wyjaśnienia.')},{title:cmsText('HomePage-v2-step-2','2. Funkcje i zakres'),text:cmsText('HomePage-v2-step-2-body','Scenariusze, podział odpowiedzialności oraz zakres prac i wyceny.')},{title:cmsText('HomePage-v2-step-3','3. Uruchomienie i odbiór'),text:cmsText('HomePage-v2-step-3-body','Sprawdzenie uzgodnionych funkcji, instruktaż i przekazanie ustalonych materiałów.')}].map(item=><article key={item.title} className="p-6 border border-[#17211C]/10 rounded-xl"><h3 className="font-semibold text-lg mb-2">{item.title}</h3><p className="text-sm text-[#17211C]/75 leading-relaxed">{item.text}</p></article>)}</div><div className="mt-7 flex flex-wrap gap-6 text-sm font-semibold text-[#0E4637]"><button onClick={()=>onNavigate('projects')} className="underline underline-offset-4">{cmsText('HomePage-v2-examples','Zobacz przykłady rozwiązań')}</button><button onClick={()=>onNavigate('knowledge','knx-dla-inwestora')} className="underline underline-offset-4">{cmsText('HomePage-v2-guide','Przeczytaj poradnik KNX dla inwestora')}</button></div></div></section>
  <section id="kontakt-rzuty" className="py-12 sm:py-16 border-t border-[#17211C]/10"><div className={wrap+' grid lg:grid-cols-2 gap-8 items-start'}><div><p className="text-xs uppercase tracking-widest text-[#0E4637] font-semibold mb-3">{cmsText('HomePage-v2-contact-kicker','Zacznijmy od rozmowy')}</p><h2 className="text-3xl sm:text-4xl font-bold font-display">{cmsText('HomePage-v2-contact-title','Masz rzut, pomysł albo pierwsze pytania?')}</h2><p className="text-[#17211C]/75 mt-5 leading-relaxed">{cmsText('HomePage-v2-contact-body','Napisz, dla kogo powstaje przestrzeń i na jakim etapie jest projekt. Nie potrzebujesz pełnej dokumentacji, żeby się z nami skontaktować.')}</p></div><ContactForm onOpenPrivacy={onOpenPrivacy} sourceContext="Rozmowa o projekcie KNX"/></div></section>
 </div>;
};
