import React from 'react';
import {cmsText} from '../cms/content.ts';
import {MapPin,ArrowUpRight,FileText,Palette,MessageCircle} from 'lucide-react';
export const ShowroomPage:React.FC<{onOpenConsultation:()=>void}>=({onOpenConsultation})=><div>
 <section className="bg-[#17211C] text-white py-12 lg:py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-xs uppercase tracking-widest text-[#E6F15A] mb-4">{cmsText('ShowroomPage-v2-kicker','Salon Delitech · Warszawa')}</p><h1 className="text-4xl sm:text-5xl font-display font-bold max-w-3xl">{cmsText('ShowroomPage-v2-title','Spotkajmy się z projektem przy jednym stole.')}</h1><p className="mt-6 text-lg text-white/80 max-w-2xl leading-relaxed">{cmsText('ShowroomPage-v2-intro','Architekt, inwestor i techniczne pytania o wnętrze. W salonie porozmawiamy o osprzęcie, sposobie obsługi i decyzjach potrzebnych przed wykonaniem instalacji.')}</p></div></section>
 <section className="py-12 sm:py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-8">
  <div className="bg-white rounded-2xl border border-[#17211C]/10 p-7 sm:p-9 space-y-5"><MapPin size={32} className="text-[#0E4637]"/><h2 className="text-2xl font-display font-bold">{cmsText('ShowroomPage-v2-address','ul. Konwaliowa 7 lok. 103')}</h2><p className="text-lg">{cmsText('ShowroomPage-v2-city','03-194 Warszawa')}</p><p className="text-sm text-[#17211C]/75">{cmsText('ShowroomPage-v2-appointment','Spotkania po wcześniejszym uzgodnieniu. Przed przyjazdem potwierdźmy termin, temat rozmowy oraz dostępność interesujących Cię próbek.')}</p><button onClick={onOpenConsultation} className="rounded-lg bg-[#0E4637] text-[#E6F15A] px-5 py-3 font-semibold text-sm">{cmsText('ShowroomPage-v2-cta','Uzgodnij wizytę')}</button><a href="https://maps.google.com/?q=Konwaliowa+7+lok.+103%2C+03-194+Warszawa" target="_blank" rel="noopener noreferrer" className="flex gap-2 items-center text-[#0E4637] text-sm font-semibold underline underline-offset-4">{cmsText('ShowroomPage-v2-map','Sprawdź dojazd w Google Maps')}<ArrowUpRight size={16}/></a></div>
  <div className="space-y-6"><h2 className="text-2xl font-bold font-display">{cmsText('ShowroomPage-v2-prepare','Co warto zabrać na spotkanie?')}</h2>{[{icon:FileText,title:cmsText('ShowroomPage-v2-plans-title','Rzut lub szkic'),body:cmsText('ShowroomPage-v2-plans-body','Wstępna koncepcja wystarczy, żeby zacząć rozmowę. Zaznacz miejsca, które budzą pytania.')},{icon:Palette,title:cmsText('ShowroomPage-v2-materials-title','Materiały i inspiracje'),body:cmsText('ShowroomPage-v2-materials-body','Kolory ścian, próbki mebli lub zdjęcia wnętrza pomogą porównać wygląd osprzętu. Wybrane modele i wykończenia uzgodnijmy wcześniej.')},{icon:MessageCircle,title:cmsText('ShowroomPage-v2-functions-title','Kilka codziennych sytuacji'),body:cmsText('ShowroomPage-v2-functions-body','Co ma się dziać rano, przy wyjściu lub wieczorem? Wspólnie uporządkujemy funkcje, zamiast zaczynać od listy urządzeń.')}].map(item=><div className="flex gap-4" key={item.title}><item.icon className="text-[#0E4637] shrink-0 mt-1" size={23}/><div><h3 className="font-semibold text-lg">{item.title}</h3><p className="text-sm text-[#17211C]/75 mt-2 leading-relaxed">{item.body}</p></div></div>)}</div>
 </div></section>
 <section className="border-t border-[#17211C]/10 bg-white py-10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-wrap items-center justify-between gap-5"><div><h2 className="text-xl font-bold">{cmsText('ShowroomPage-v2-pack-title','Przygotuj brief przed wizytą')}</h2><p className="text-sm text-[#17211C]/75 mt-2">{cmsText('ShowroomPage-v2-pack-body','Skorzystaj z przykładowej karty pomieszczenia i listy pytań z pakietu dla architekta.')}</p></div><a href="/materialy/pakiet-architekta.html" className="px-5 py-3 rounded-lg border border-[#0E4637]/25 text-[#0E4637] font-semibold text-sm">{cmsText('ShowroomPage-v2-pack-cta','Otwórz pakiet')}</a></div></section>
</div>;
